import Action from "@/app/components/action";
import Sidebar from "@/app/components/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "BookShelf",
  description: "Generated by BookShelf",
};

export default function AdminHomepageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full h-screen py-8 px-6">
      <div className="w-1/6 bg-white flex justify-center rounded-s-lg">
        <Sidebar />
      </div>
      <div className="w-5/6 bg-slate-100 rounded-e-lg flex flex-col">
        <div className=""></div>
        <div className="mx-8 w-fit"></div>
        <div className="overflow-auto">
          <div>
            <div className="flex justify-between items-center pt-6 pb-4 mx-8">
              {/* <Search /> */}
              <div></div>
              <Action />
            </div>
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
