import type { Metadata } from "next";
import Sidebar from "../components/sidebar";

export const metadata: Metadata = {
  title: "BookShelf",
  description: "Generated by BookShelf",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-[url('/assets/images/bg.png')] h-screen bg-cover">
      <div className="flex w-full h-screen py-8 px-6">
        <div className="w-1/6 bg-white flex justify-center rounded-s-lg">
          <Sidebar />
        </div>
        <div className="w-5/6 bg-slate-100 rounded-e-lg flex flex-col">
          <div className=""></div>
          <div className="mx-8 w-fit"></div>
          <div className="overflow-auto">{children}</div>
        </div>
      </div>
    </div>
  );
}
